export default {
  1: { title: 'English', code: 'en-US' },
  2: { title: 'Russian', code: 'ru-RU' },
  3: { title: 'German', code: 'de-DE' },
  4: { title: 'French', code: 'fr-FR' },
  5: { title: 'Spanish', code: 'es-ES' },
  8: { title: 'Croatian', code: 'hr-HR' },
  10: { title: 'Arabic', code: 'ar-AE' },
  11: { title: 'Portuguese', code: 'pt-PT' },
  12: { title: 'Lithuanian', code: 'lt-LT' },
  13: { title: 'Romanian', code: 'ro-RO' },
  14: { title: 'Polish', code: 'pl-PL' },
  15: { title: 'Hungarian', code: 'hu-HU' },
  16: { title: 'Czech', code: 'cs-CZ' },
  17: { title: 'Chinese', code: 'zh' },
  22: { title: 'Danish', code: 'da-DK' },
  23: { title: 'Italian', code: 'it-IT' },
  24: { title: 'Dutch', code: 'nl-NL' },
  26: { title: 'Estonian', code: 'et' },
  27: { title: 'Latvian', code: 'lv-LV' },
  28: { title: 'Japanese', code: 'ja-JP' },
  29: { title: 'Swedish', code: 'sv-SE' },
  30: { title: 'Norwegian (Bokmål)', code: 'nb-NO' },
  32: { title: 'Turkish', code: 'tr-TR' },
  33: { title: 'Ukrainian', code: 'uk-UA' },
  36: { title: 'Finnish', code: 'fi-FI' },
  37: { title: 'Latin', code: 'la' },
  38: { title: 'Greek', code: 'el-GR' },
  39: { title: 'Korean', code: 'ko-KR' },
  49: { title: 'Irish', code: 'ga' },
  53: { title: 'Catalan', code: 'ca-ES' },
  60: { title: 'Slovak', code: 'sk-SK' },
  67: { title: 'Slovenian', code: 'sl-SI' },
  68: { title: 'Basque', code: 'eu-ES' },
  78: { title: 'Maltese', code: 'mt' },
  97: { title: 'Chinese simplified', code: 'zh' },
  98: { title: 'Chinese (Taiwan)', code: 'zh-TW' }
};
