export default {
  1: { title: 'English', code: 'EN' },
  2: { title: 'Russian', code: 'RU' },
  3: { title: 'German', code: 'DE' },
  4: { title: 'French', code: 'FR' },
  5: { title: 'Spanish', code: 'ES' },
  8: { title: 'Croatian', code: 'HR' },
  10: { title: 'Arabic', code: 'AR' },
  11: { title: 'Portuguese', code: 'PT' },
  12: { title: 'Lithuanian', code: 'LT' },
  13: { title: 'Romanian', code: 'RO' },
  14: { title: 'Polish', code: 'PL' },
  15: { title: 'Hungarian', code: 'HU' },
  16: { title: 'Czech', code: 'CS' },
  17: { title: 'Chinese', code: 'ZH' },
  22: { title: 'Danish', code: 'DA' },
  23: { title: 'Italian', code: 'IT' },
  24: { title: 'Dutch', code: 'NL' },
  26: { title: 'Estonian', code: 'ET' },
  27: { title: 'Latvian', code: 'LV' },
  28: { title: 'Japanese', code: 'JA' },
  29: { title: 'Swedish', code: 'SV' },
  30: { title: 'Norwegian (Bokmål)', code: 'NB' },
  32: { title: 'Turkish', code: 'TR' },
  33: { title: 'Ukrainian', code: 'UK' },
  36: { title: 'Finnish', code: 'FI' },
  37: { title: 'Latin', code: 'LA' },
  38: { title: 'Greek', code: 'EL' },
  39: { title: 'Korean', code: 'KO' },
  49: { title: 'Irish', code: 'GA' },
  53: { title: 'Catalan', code: 'CA' },
  60: { title: 'Slovak', code: 'SK' },
  67: { title: 'Slovenian', code: 'SL' },
  68: { title: 'Basque', code: 'EU' },
  78: { title: 'Maltese', code: 'MT' },
  97: { title: 'Chinese simplified', code: 'ZH simp.' },
  98: { title: 'Chinese (Taiwan)', code: 'ZH Tw.' }
};
